language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-setuptools python3-setuptools
  - python setup.py install
script: ./test/run-tests.sh
branches:
  only:
  - master
